icpc-frontned/src/app/components/navbar.tsx, icpc-frontned/src/app/page.tsx
Created the navbar component inside the "components" folder
=> features: navbar, "./components"

icpc-frontned/src/app/components/NavbarComponent.tsx
The order of the options in the NavbarComponent has been modified according to client requirements
=> Change (NavbarComponent) changed order of options

icpc-frontned/package-lock.json, icpc-frontned/package.json, icpc-frontned/src/app/components/TagComponent.tsx, icpc-frontned/src/app/components/TagListComponent.tsx, icpc-frontned/src/app/components/cards/NoteCardComponent.tsx, icpc-frontned/src/app/note/apunte.json, icpc-frontned/src/app/note/page.tsx
The page includes a NoteCardComponent that organizes the content Includes a TagListComponent that displays the tags of the note Every tag takes its name and color from a json file The markdown interpreter has been added to the project
It is still necessary to add markdown for math symbols and formulas
=> Add (Note page) Created a page to display a note WIP

icpc-frontned/package-lock.json, icpc-frontned/src/app/components/forms/TagSelectorComponent.tsx, icpc-frontned/src/app/components/forms/TextAreaComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx
Integrated the TagSelector component to add tags to the note object
Installed chroma-js for styling purposes
=> fix(Create Note Modal): Create a popup form to write a note article

icpc-frontned/src/app/notelist/page.tsx
Removed a CreateNoteComponent from "/notelist" that was inserted there for testing purposes
=> fix(/notelist): Create a popup form to write a note article

icpc-frontned/src/app/components/NavbarComponent.tsx
Added links for the "/newslist" and "/about" pages
=> fix(NavbarComponent): Add links to the news and about pages

icpc-frontned/src/app/components/cards/NoteCardComponent.tsx, icpc-frontned/src/app/components/tags/TagListComponent.tsx
Added vertical margin to the TagListComponent
Added vertical margin to the exercise button below the card
=> refactor(NoteCardComponent): Add margin to the TagList component

icpc-frontned/src/app/components/NewsListComponent.tsx
Implemented lazy import of the NewsItemComponent. Every Item in the list is surrounded by a Suspense tag
Lazy import of the NewsItemComponent, Imported Suspense tag from react
=> feat(NewsList): Implement lazy loading in the page

icpc-frontned/src/app/components/NewsListComponent.tsx
Added a title on the top of the news list
=> fix(NewsList): Add a title to the "/newslist" page

icpc-backend/src/auth/auth.controller.ts, icpc-backend/src/auth/auth.service.ts, icpc-backend/src/auth/dto/login.dto.ts, icpc-backend/src/auth/dto/register.dto.ts, icpc-backend/src/users/dto/create-user.dto.ts, icpc-backend/src/users/entities/user.entity.ts, icpc-backend/src/users/users.service.ts
First and last name fields are added for the registration form and response formats are added for the login.
=> refactor: :recycle: Update user and authentication entities and DTOs

icpc-backend/src/categories/categories.service.ts, icpc-backend/src/categories/entities/category.entity.ts, icpc-backend/src/difficulty/difficulty.controller.ts, icpc-backend/src/difficulty/entities/difficulty.entity.ts, icpc-backend/src/excercises/dto/create-excercise.dto.ts, icpc-backend/src/excercises/entities/excercise.entity.ts, icpc-backend/src/excercises/excercises.controller.ts, icpc-backend/src/excercises/excercises.module.ts, icpc-backend/src/excercises/excercises.service.ts, icpc-backend/src/memory/memory.controller.ts, icpc-backend/src/memory/memory.service.ts, icpc-backend/src/tags/tags.controller.ts, icpc-backend/src/time/entities/time.entity.ts, icpc-backend/src/time/time.controller.ts, icpc-backend/src/time/time.service.ts, icpc-frontned/src/app/components/dropdowns/SelectComponent.tsx, icpc-frontned/src/app/components/forms/TagSelectorComponent.tsx, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx, icpc-frontned/src/app/dev/page.tsx, icpc-frontned/src/constants/types.ts, icpc-frontned/src/store/useExcerciseStore.ts, icpc-frontned/src/store/useUtilsStore.ts
Allow trainers and administrators to upload excercises to the database
Created a new form component which can be tested at /dev. Created excerciseStore and UtilsStore
Changed relationship between Category and Excercise from ManyToMany to One Category to Many Excercise.
Created relationships between Excercise, TimeLImit and MemoryLimit.
Removed token verification for GET requests in Tags, Memory, Time, Difficulty and Category.
Created new interfaces in types.ts to represent TimeLimit, MemoryLImit, etc.
=> feat(excerciseUpload): Allow trainers and administrators to upload excercises

icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/modals/CreateNewsComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx, icpc-frontned/src/app/dev/page.tsx
Removed useForms as parameter for form modals
Removed 'use client' directive from /dev/page.tsx
Modified structure of CreateNotesComponent and CreateNewsComponent to include a form tag and onSubmit function
Moved CreateNewsComponent from /cards folder to /modals folder
Currently all Create___Component take no props
=> fix(useForm): Remove useForm as parameter for form modals

icpc-backend/src/excercises/dto/create-excercise.dto.ts, icpc-backend/src/excercises/excercises.service.ts, icpc-frontned/package-lock.json, icpc-frontned/package.json, icpc-frontned/src/app/components/dropdowns/InputSelectorComponent.tsx, icpc-frontned/src/app/components/dropdowns/SelectComponent.tsx, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/modals/CreateNewsComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx, icpc-frontned/src/constants/types.ts, icpc-frontned/src/store/useExcerciseStore.ts
Fixed SelectComponent.tsx dependent on Headless UI
Now it is able to display correctly the placeholder text and the currently selected value
Tested: It correctly returns a string value
=> Fixes/omar/upgrade headless UI

icpc-frontned/src/app/components/dropdowns/InputSelectorCreateComponent.tsx, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/constants/types.ts, icpc-frontned/src/store/useUtilsStore.ts
Created a new InputSelectorComponent, which is a searchable single value select input field without the ability to create new registries in the database.
Created a new InputSelectorCreateComponent which is a single value searchable select input with the ability to create new registries in the database. This takes a handleCreate function as a prop to execute once a non-existent value is written in the component's search bar.
Both of these components use the react-select library
=> feat(InputSelectorComponent, InputSelectorCreateComponent): Allow users to search in select components and create new values

icpc-backend/src/categories/categories.service.ts, icpc-backend/src/categories/entities/category.entity.ts, icpc-backend/src/comment/entities/comment.entity.ts, icpc-backend/src/notes/dto/create-note.dto.ts, icpc-backend/src/notes/entities/note.entity.ts, icpc-backend/src/notes/notes.service.ts
Established relations between notes, comments and categories. Modified Note DTO to include Tags
=> feat(NoteUpload): Allow trainers and administrators to upload notes

icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx, icpc-frontned/src/app/dev/page.tsx, icpc-frontned/src/store/useNoteStore.ts
Created a new NoteStore to handle Note related request to API. Created method createNote to collect the form data and send it to the database
=> feat(Create Notes): Implement note uploading in front-end component

icpc-frontned/src/app/components/forms/ImageInputComponent.tsx, icpc-frontned/src/app/components/modals/CreateNewsComponent.tsx
Used React useState to draw a preview of the selected file, changed text color to adapt to dark mode
=> fix(ImageInputComponent): Show Image preview

icpc-frontned/next.config.mjs, icpc-frontned/package-lock.json, icpc-frontned/package.json, icpc-frontned/src/app/components/NewsListComponent.tsx, icpc-frontned/src/app/components/cards/NewsCardComponent.tsx, icpc-frontned/src/app/components/cards/NewsItemComponent.tsx, icpc-frontned/src/app/components/panels/NewsBodyComponent.tsx, icpc-frontned/src/app/news/[id]/page.tsx, icpc-frontned/src/app/newslist/page.tsx, icpc-frontned/src/constants/types.ts, icpc-frontned/src/store/useNewsStore.ts, icpc-frontned/src/store/useUtilsStore.ts
Modified the News List Component, News Item Component and other relevant components to gather the news articles from the database, display them in a list and redirect the user to a page of that news article
It doesn't display images. Next.js updated to version 14.2.4
=> feat(NewsList): Make the page collect news from the database

icpc-backend/src/auth/auth.service.ts, icpc-backend/src/auth/dto/login.dto.ts, icpc-backend/src/excercises/dto/create-excercise.dto.ts, icpc-backend/src/excercises/entities/excercise.entity.ts, icpc-backend/src/excercises/excercises.controller.ts, icpc-backend/src/excercises/excercises.module.ts, icpc-backend/src/excercises/excercises.service.ts, icpc-backend/src/image/image.controller.ts, icpc-backend/src/news/dto/create-news.dto.ts, icpc-backend/src/news/news.controller.ts, icpc-backend/src/news/news.module.ts, icpc-backend/src/news/news.service.ts, icpc-backend/src/notes/dto/create-note.dto.ts, icpc-backend/src/notes/notes.module.ts, icpc-backend/src/notes/notes.service.ts, icpc-backend/src/users/users.service.ts, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/modals/CreateNewsComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx, icpc-frontned/src/app/dev/page.tsx, icpc-frontned/src/store/useExcerciseStore.ts, icpc-frontned/src/store/useNewsStore.ts, icpc-frontned/src/store/useNoteStore.ts, icpc-frontned/src/store/useStore.ts
The backend now automatically creates ticket whenever a trainer or admin creates an exercise, note or news article
=> feat(Ticket Creation): Create tickets when an item is created

icpc-backend/src/categories/categories.service.ts, icpc-backend/src/difficulty/difficulty.service.ts, icpc-backend/src/excercises/dto/create-excercise.dto.ts, icpc-backend/src/excercises/dto/get-exercise-list.dto.ts, icpc-backend/src/excercises/excercises.controller.ts, icpc-backend/src/excercises/excercises.service.ts, icpc-backend/src/news/news.service.ts, icpc-backend/src/tags/tags.service.ts, icpc-frontned/src/app/components/dropdowns/InputSelectorComponent.tsx, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/tables/TableComponent.tsx, icpc-frontned/src/app/components/tags/TagComponent.tsx, icpc-frontned/src/app/dev/page.tsx, icpc-frontned/src/app/exercises/page.tsx, icpc-frontned/src/constants/types.ts, icpc-frontned/src/store/useExcerciseStore.ts
Created functions in the store and backend to fetch a list of exercises according to filters. Created a new API endpoint to get a list of exercises. Inserted slight modifications and corrections to the TagComponent and CreateExcerciseComponent
=> feat(ExerciseList): Connect the list page to the database

icpc-backend/src/ticket/ticket.service.ts
Modified the findOne function in the ticket service to collect the item data
=> fix(ticket service): Get the item data from the ticket id

icpc-frontned/src/app/ticket/[id]/page.tsx
Removed the state and effect hooks to make the page server-side rendered
=> fix(ticket page): Converted the ticket page to a server component

icpc-backend/src/excercises/entities/excercise.entity.ts, icpc-backend/src/news/entities/news.entity.ts, icpc-backend/src/news/news.service.ts, icpc-backend/src/notes/entities/note.entity.ts, icpc-backend/src/ticket/ticket.controller.ts, icpc-backend/src/ticket/ticket.service.ts, icpc-frontned/src/app/components/tables/ProfileTableComponent.tsx, icpc-frontned/src/app/page.tsx, icpc-frontned/src/app/profile/page.tsx, icpc-frontned/src/constants/types.ts, icpc-frontned/src/store/useStore.ts, icpc-frontned/src/store/useUtilsStore.ts
Created new routes on the backend to collect pending tickets, reports and user accounts
=> fix(profileTable): All tabs on the table show relevant information

icpc-backend/src/categories/categories.service.ts, icpc-backend/src/difficulty/difficulty.service.ts, icpc-backend/src/excercises/dto/create-excercise.dto.ts, icpc-backend/src/excercises/excercises.service.ts, icpc-backend/src/memory/memory.service.ts, icpc-backend/src/tags/tags.service.ts, icpc-backend/src/ticket/entities/ticket.entity.ts, icpc-backend/src/time/time.service.ts, icpc-frontned/.eslintrc.json, icpc-frontned/src/app/components/tables/TableComponent.tsx, icpc-frontned/src/constants/types.ts
The create functions of the categories, difficulty, memory, tags and time modules insert a ticket in the database. New item types were created: 'UTILS' and 'USER'
=> fix(tickets): The creation of secondary items creates tickets

icpc-backend/package-lock.json, icpc-backend/package.json, icpc-backend/src/difficulty/difficulty.service.ts, icpc-backend/src/tags/dto/create-tag.dto.ts, icpc-backend/src/time/time.service.ts, icpc-frontned/src/app/components/dropdowns/SelectComponent.tsx, icpc-frontned/src/app/components/forms/ColorPickerComponent.tsx, icpc-frontned/src/app/components/forms/TextFieldComponent.tsx, icpc-frontned/src/app/components/modals/CreateCategoryComponent.tsx, icpc-frontned/src/app/components/modals/CreateDifficultyComponent.tsx, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/modals/CreateMemoryComponent.tsx, icpc-frontned/src/app/components/modals/CreateNewsComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx, icpc-frontned/src/app/components/modals/CreateTagComponent.tsx, icpc-frontned/src/app/components/modals/CreateTimeComponent.tsx, icpc-frontned/src/app/components/tabs/TabComponent.tsx, icpc-frontned/src/store/useUtilsStore.ts
Modified the different modals to include a button to reset the values of the fields in the form
Attached the modals to the tabs in the user profile table
=> Alan modals

icpc-backend/src/excercises/excercises.service.ts, icpc-backend/src/ticket/ticket.controller.ts, icpc-backend/src/ticket/ticket.service.ts, icpc-frontned/next.config.mjs, icpc-frontned/src/app/components/tables/ProfileTableComponent.tsx, icpc-frontned/src/app/profile/page.tsx, icpc-frontned/src/app/ticket/TicketActions.tsx, icpc-frontned/src/store/useUtilsStore.ts
Modificacion en backend y en frontned para que no
se puedan editar Items con tickets en estado pendiente.
=> Este comit esta pendiente, no puede ser editado D:

icpc-backend/src/excercises/excercises.service.ts, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/tables/ProfileTableComponent.tsx, icpc-frontned/src/app/components/tabs/TabComponent.tsx
=> Modificación en el TabComponent

icpc-frontned/src/app/components/cards/CardWithHeaderComponent.tsx, icpc-frontned/src/app/components/tags/TagComponent.tsx
Ahora se puede modificar la logica de cambio de color de texto en los tags
=> Mejorada la logica de discriminacion

icpc-backend/src/notes/notes.service.ts, icpc-backend/src/users/users.service.ts, icpc-frontned/package-lock.json, icpc-frontned/src/app/components/tables/ProfileTableComponent.tsx, icpc-frontned/src/app/profile/page.tsx
Added a BadRequestException to the length of the description of a note
=> Dejnme ser libre

icpc-backend/src/categories/categories.service.ts, icpc-backend/src/memory/memory.service.ts, icpc-backend/src/tags/tags.service.ts, icpc-backend/src/time/time.service.ts, icpc-frontned/src/app/components/modals/CreateTimeComponent.tsx
Categorías
Modificar: Se podía modificar una categoría para que tuviera el mismo nombre que una ya existente, pero esto fue corregido.
Etiquetas
Modificar: Se presentaba un "Internal server error" al intentar asignar el mismo nombre a dos etiquetas, lo cual ya fue solucionado.
Límites de tiempo
Crear: Al borrar los datos ingresados en un nuevo límite de tiempo, solo se podía hacer una vez, ya que las siguientes veces el botón no tenía efecto. Este problema ya fue resuelto.
Modificar: Se emitía un mensaje de "Internal server error" al intentar modificar un límite de tiempo a un valor ya existente. Este error fue corregido y ya no ocurre.
Memoria
Crear: Se generaba un "Internal server error" al intentar agregar un valor de memoria que ya estaba registrado. Ahora, el sistema maneja …
=> Tanda de errores solucionados

icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx
No pude mover ni remover la distancia de mis labios de los tuyos bb >.<
=> Se movio la ubicacion de Tag en CreateExcercise

icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/modals/CreateNewsComponent.tsx, icpc-frontned/src/app/components/modals/CreateNoteComponent.tsx
=> No mames solo borre una pendejada, que loco

icpc-frontned/src/app/components/NoteItemComponent.tsx, icpc-frontned/src/app/components/NoteListComponent.tsx, icpc-frontned/src/app/components/cards/CardWithHeaderComponent.tsx, icpc-frontned/src/app/components/cards/ExerciseCardComponent.tsx, icpc-frontned/src/app/components/modals/ReportCardComponent.tsx, icpc-frontned/src/app/components/panels/MarkdownBodyComponent.tsx, icpc-frontned/src/app/components/tables/ProfileTableComponent.tsx, icpc-frontned/src/app/components/tables/TableComponent.tsx, icpc-frontned/src/app/components/tabs/TabComponent.tsx, icpc-frontned/src/app/components/ui/ExerciseHeaderComponent.tsx, icpc-frontned/src/app/exercises/[exercise]/page.tsx, icpc-frontned/src/app/layout.tsx, icpc-frontned/src/app/login/page.tsx, icpc-frontned/src/app/page.tsx, icpc-frontned/src/app/profile/page.tsx
Aqui reajustando la pagina de la misma forna en la que me reajustaron los intestinos esas carnitas de los Toños.
Pd: Esa minita esta armada.
=> Errores varios solucionados

icpc-backend/src/excercises/excercises.service.ts, icpc-frontned/next.config.mjs, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx
Se agregaron validaciones sobre la longitud de ciertos campos para retornar errores cuando el usuario se pase de caracteres
=> Validaciones en los campos de crear ejercicio

icpc-backend/src/difficulty/difficulty.service.ts, icpc-frontned/src/app/components/modals/CreateCategoryComponent.tsx, icpc-frontned/src/app/components/modals/CreateDifficultyComponent.tsx, icpc-frontned/src/app/components/modals/CreateMemoryComponent.tsx, icpc-frontned/src/app/components/modals/CreateTagComponent.tsx, icpc-frontned/src/app/components/modals/CreateTimeComponent.tsx
Se han cambiado los modales de CreateDifficultyComponent CreateDifficultyComponent, CreateMemoryComponent, CreateTagComponent y CreateTimeComponent para que se muestren de forma correcta al abir sus formularios.
Anteriormente mostraban la informacion previamente almacenada en estos si se habian utilizado previamente, ahora olvidaran esta informacion al abrise, no como tu, que no olvidas a tu ex.
=> Cambios de mostrado de formularios varios

icpc-backend/src/excercises/excercises.service.ts
=> Escercises.Service perron ahora si mamalon chingon

icpc-frontned/src/app/components/cards/ExerciseCardComponent.tsx, icpc-frontned/src/app/components/modals/CreateExcerciseComponent.tsx, icpc-frontned/src/app/components/ui/ExerciseMarkdownComponent.tsx
Se modificaron los componentes para que se puedan subir y mostrar las entradas, salidas y restricciones de los problemas con saltos de linea, ahora puedes crear 255 lineas, cada una con un unico caracter y destrozar la fe en la humanidad de alguien mas! :D
=> Create Exercise con saltos de linea.

icpc-backend/src/excercises/excercises.service.ts
Modified the database query in the getList method of the exercise service to order the exercises first by difficulty followed by name in alphabetical order
=> Cambio en como se ordenan los ejercicios

icpc-backend/src/excercises/excercises.controller.ts, icpc-backend/src/notes/notes.controller.ts, icpc-backend/src/services/logger.service.ts, icpc-frontned/src/app/exercises/[exercise]/page.tsx, icpc-frontned/src/app/note/[id]/page.tsx, icpc-frontned/src/store/useExcerciseStore.ts, icpc-frontned/src/store/useNoteStore.ts
Added a function to log every time a user that has not logged in has visited a note or exercise page. This is made to track which are the most visited topics and exercises
=> feat(itemLogs): Log GET operations

icpc-backend/src/excercises/excercises.module.ts, icpc-backend/src/excercises/excercises.service.ts, icpc-backend/src/mailer/mailer.module.ts, icpc-backend/src/mailer/mailer.service.ts, icpc-backend/src/news/news.module.ts, icpc-backend/src/news/news.service.ts, icpc-backend/src/notes/notes.module.ts, icpc-backend/src/notes/notes.service.ts, icpc-backend/src/report/report.module.ts, icpc-backend/src/report/report.service.ts, icpc-backend/src/users/users.module.ts, icpc-backend/src/users/users.service.ts
Changed the way the sendMail function gathered addresses to send emails. Created a new getMails function in the users service to collect email addresses for their use in the sendMail function
=> fix(Mailer): Send emails to all accounts
